version: '3'
services:
  jenkins:
    restart: always
    user: root
    image: jenkins/dockerselenium
    build:
       context: dockerjenkins
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkinsdocker
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/sshjenkins:/root/.ssh
    networks:
      - net
  postgres:
    restart: always
    image: postgres:14
    container_name: postgres
    networks:
      - net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonarpasswd
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
  sonarqube:
    restart: always
    image: sonarqube:lts
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
    networks:
      - net
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonarpasswd
      - SONARQUBE_JDBC_URL="jdbc:postgresql://postgres:5432/sonar"
    depends_on:
      - postgres
    volumes:
     - ~/sonarqube/data:/opt/sonarqube/data
     - ~/sonarqube/logs:/opt/sonarqube/logs
     - ~/sonarqube/extensions:/opt/sonarqube/extensions
  nexus:
    restart: always
    image: sonatype/nexus3
    container_name: nexus
    ports:
     - 8081:8081
    networks:
      - net
    volumes:
      - ~/nexus-data:/nexus-data
networks:
  net:
